// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plan10K12Uker.Api.Data;

#nullable disable

namespace Plan10K12Uker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plan10K12Uker.Api.Domain.Block", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("FirstWeek")
                        .HasColumnType("integer")
                        .HasColumnName("first_week");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("focus");

                    b.Property<int>("LastWeek")
                        .HasColumnType("integer")
                        .HasColumnName("last_week");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.ToTable("blocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_blocks_weeks", "first_week >= 1 AND last_week <= 12 AND first_week <= last_week");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstWeek = 1,
                            Focus = "Bryte platå, øke VO2max",
                            LastWeek = 4,
                            Name = "Blokk 1"
                        },
                        new
                        {
                            Id = 2,
                            FirstWeek = 5,
                            Focus = "Øke kapasitet, øke FTP",
                            LastWeek = 8,
                            Name = "Blokk 2"
                        },
                        new
                        {
                            Id = 3,
                            FirstWeek = 9,
                            Focus = "Peak vinterform, maksimal fettmobilisering",
                            LastWeek = 12,
                            Name = "Blokk 3"
                        });
                });

            modelBuilder.Entity("Plan10K12Uker.Api.Domain.NutritionGuideline", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("day_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Meal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meal");

                    b.HasKey("Id")
                        .HasName("pk_nutrition_guidelines");

                    b.HasIndex("Meal", "DayType")
                        .IsUnique()
                        .HasDatabaseName("ix_nutrition_guidelines_meal_day_type");

                    b.ToTable("nutrition_guidelines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayType = "Rest",
                            Description = "Protein shake + peanut butter + berries",
                            Meal = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            DayType = "Training",
                            Description = "Protein shake + peanut butter + banana or bread slice",
                            Meal = "Breakfast"
                        },
                        new
                        {
                            Id = 3,
                            DayType = "Any",
                            Description = "Salad + eggs + mackerel + extra protein",
                            Meal = "Lunch"
                        },
                        new
                        {
                            Id = 4,
                            DayType = "Any",
                            Description = "Chicken, cod or beef + vegetables + carbs after hard sessions",
                            Meal = "Dinner"
                        },
                        new
                        {
                            Id = 5,
                            DayType = "Any",
                            Description = "Chocolate Saturdays, moderate alcohol",
                            Meal = "Snacks"
                        });
                });

            modelBuilder.Entity("Plan10K12Uker.Api.Domain.PlannedSession", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("BlockId")
                        .HasColumnType("integer")
                        .HasColumnName("block_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_planned_sessions");

                    b.HasIndex("BlockId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_planned_sessions_block_id_day_of_week");

                    b.ToTable("planned_sessions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 11,
                            BlockId = 1,
                            DayOfWeek = 1,
                            Description = "Run 4x4 intervals"
                        },
                        new
                        {
                            Id = 12,
                            BlockId = 1,
                            DayOfWeek = 2,
                            Description = "Strength: squat, deadlift, row, hip thrust"
                        },
                        new
                        {
                            Id = 13,
                            BlockId = 1,
                            DayOfWeek = 3,
                            Description = "Zwift Z2 60–75 min"
                        },
                        new
                        {
                            Id = 14,
                            BlockId = 1,
                            DayOfWeek = 4,
                            Description = "Zwift VO2 6x2 min"
                        },
                        new
                        {
                            Id = 15,
                            BlockId = 1,
                            DayOfWeek = 5,
                            Description = "Strength: lunge, step-up, press, pulldown"
                        },
                        new
                        {
                            Id = 16,
                            BlockId = 1,
                            DayOfWeek = 6,
                            Description = "Run Z2 5–10 km"
                        },
                        new
                        {
                            Id = 10,
                            BlockId = 1,
                            DayOfWeek = 0,
                            Description = "Bike Z2 2–3 h or rest"
                        },
                        new
                        {
                            Id = 21,
                            BlockId = 2,
                            DayOfWeek = 1,
                            Description = "Run 4x4/5x4 progression"
                        },
                        new
                        {
                            Id = 22,
                            BlockId = 2,
                            DayOfWeek = 2,
                            Description = "Strength heavy: squat 5x5, deadlift 4x5"
                        },
                        new
                        {
                            Id = 23,
                            BlockId = 2,
                            DayOfWeek = 3,
                            Description = "Zwift Z2 60–90 min"
                        },
                        new
                        {
                            Id = 24,
                            BlockId = 2,
                            DayOfWeek = 4,
                            Description = "Zwift FTP 2x20 or 3x12"
                        },
                        new
                        {
                            Id = 25,
                            BlockId = 2,
                            DayOfWeek = 5,
                            Description = "Strength volume: lunge, step-ups, press, pulldown"
                        },
                        new
                        {
                            Id = 26,
                            BlockId = 2,
                            DayOfWeek = 6,
                            Description = "Run Z2 8–12 km"
                        },
                        new
                        {
                            Id = 20,
                            BlockId = 2,
                            DayOfWeek = 0,
                            Description = "Bike Z2 or rest"
                        },
                        new
                        {
                            Id = 31,
                            BlockId = 3,
                            DayOfWeek = 1,
                            Description = "Run VO2 10x1 or 6x3"
                        },
                        new
                        {
                            Id = 32,
                            BlockId = 3,
                            DayOfWeek = 2,
                            Description = "Strength maintenance"
                        },
                        new
                        {
                            Id = 33,
                            BlockId = 3,
                            DayOfWeek = 3,
                            Description = "Zwift Z2 45–75 min"
                        },
                        new
                        {
                            Id = 34,
                            BlockId = 3,
                            DayOfWeek = 4,
                            Description = "Zwift VO2 8x2 or 5x3"
                        },
                        new
                        {
                            Id = 35,
                            BlockId = 3,
                            DayOfWeek = 5,
                            Description = "Rest or light strength"
                        },
                        new
                        {
                            Id = 36,
                            BlockId = 3,
                            DayOfWeek = 6,
                            Description = "Run Z2 10–14 km"
                        },
                        new
                        {
                            Id = 30,
                            BlockId = 3,
                            DayOfWeek = 0,
                            Description = "Bike Z2 or rest"
                        });
                });

            modelBuilder.Entity("Plan10K12Uker.Api.Domain.PlannedSession", b =>
                {
                    b.HasOne("Plan10K12Uker.Api.Domain.Block", "Block")
                        .WithMany("Sessions")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planned_sessions_blocks_block_id");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("Plan10K12Uker.Api.Domain.Block", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
